[package]
name = "mapserver"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"

[dependencies]
rand = "0.8"
serde = { version = "1.0.97", features = ["derive"] }
serde_json = "1.0.97"

